/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Health */
    get: operations['get_health_api_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/buckets': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Buckets */
    get: operations['list_buckets_api_buckets_get'];
    put?: never;
    /** Create Bucket */
    post: operations['create_bucket_api_buckets_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/buckets/{bucket_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Bucket */
    get: operations['get_bucket_api_buckets__bucket_id__get'];
    put?: never;
    post?: never;
    /** Delete Bucket */
    delete: operations['delete_bucket_api_buckets__bucket_id__delete'];
    options?: never;
    head?: never;
    /** Update Bucket */
    patch: operations['update_bucket_api_buckets__bucket_id__patch'];
    trace?: never;
  };
  '/api/buckets/{bucket_id}/documents': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Upload Documents */
    post: operations['upload_documents_api_buckets__bucket_id__documents_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/documents': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Documents */
    get: operations['list_documents_api_documents_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/documents/{document_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Document */
    get: operations['get_document_api_documents__document_id__get'];
    put?: never;
    post?: never;
    /** Delete Document */
    delete: operations['delete_document_api_documents__document_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/documents/{document_id}/text': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Document Text */
    get: operations['get_document_text_api_documents__document_id__text_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/documents/{document_id}/move': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Move Document */
    post: operations['move_document_api_documents__document_id__move_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/documents/{document_id}/reject': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reject Document */
    post: operations['reject_document_api_documents__document_id__reject_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Body_upload_documents_api_buckets__bucket_id__documents_post */
    Body_upload_documents_api_buckets__bucket_id__documents_post: {
      /** Files */
      files: string[];
      /**
       * Source Note
       * @default
       */
      source_note: string;
    };
    /** BucketCreate */
    BucketCreate: {
      /** Name */
      name: string;
      /**
       * Description
       * @default
       */
      description: string;
    };
    /** BucketOut */
    BucketOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Description */
      description: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      stats: components['schemas']['BucketStats'];
    };
    /** BucketStats */
    BucketStats: {
      /** Documents */
      documents: number;
      /** Parsed Documents */
      parsed_documents: number;
      /** Chars */
      chars: number;
      /** Est Tokens */
      est_tokens: number;
    };
    /** BucketUpdate */
    BucketUpdate: {
      /** Name */
      name?: string | null;
      /** Description */
      description?: string | null;
    };
    /** DocumentOut */
    DocumentOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Bucket Id
       * Format: uuid
       */
      bucket_id: string;
      /** Filename */
      filename: string;
      /** Source Format */
      source_format: string;
      /** Source Note */
      source_note: string;
      /** Status */
      status: string;
      /** Error */
      error: string | null;
      /** Content Hash */
      content_hash: string | null;
      /** Char Count */
      char_count: number;
      /** Word Count */
      word_count: number;
      /** Quality */
      quality: {
        [key: string]: unknown;
      };
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * DocumentText
     * @description A window into the cleaned text, never the whole 50MB document.
     */
    DocumentText: {
      /** Text */
      text: string;
      /** Offset */
      offset: number;
      /** Length */
      length: number;
      /** Total */
      total: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** Health */
    Health: {
      /** Status */
      status: string;
      /** Database */
      database: string;
    };
    /** MoveDocument */
    MoveDocument: {
      /**
       * Bucket Id
       * Format: uuid
       */
      bucket_id: string;
    };
    /** Page[BucketOut] */
    Page_BucketOut_: {
      /** Items */
      items: components['schemas']['BucketOut'][];
      /** Total */
      total: number;
    };
    /** Page[DocumentOut] */
    Page_DocumentOut_: {
      /** Items */
      items: components['schemas']['DocumentOut'][];
      /** Total */
      total: number;
    };
    /** RejectDocument */
    RejectDocument: {
      /**
       * Reason
       * @default
       */
      reason: string;
    };
    /**
     * UploadOutcome
     * @description One line per file the user handed us, in the order they sent them.
     */
    UploadOutcome: {
      /** Filename */
      filename: string;
      /** Status */
      status: string;
      /** Document Id */
      document_id?: string | null;
      /** Error */
      error?: string | null;
    };
    /** UploadResult */
    UploadResult: {
      /** Parsed */
      parsed: number;
      /** Failed */
      failed: number;
      /** Outcomes */
      outcomes: components['schemas']['UploadOutcome'][];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  get_health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Health'];
        };
      };
    };
  };
  list_buckets_api_buckets_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Page_BucketOut_'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_bucket_api_buckets_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['BucketCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BucketOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_bucket_api_buckets__bucket_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        bucket_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BucketOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_bucket_api_buckets__bucket_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        bucket_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_bucket_api_buckets__bucket_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        bucket_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['BucketUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BucketOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  upload_documents_api_buckets__bucket_id__documents_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        bucket_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_upload_documents_api_buckets__bucket_id__documents_post'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UploadResult'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_documents_api_documents_get: {
    parameters: {
      query?: {
        bucket_id?: string | null;
        status?: string | null;
        q?: string | null;
        flagged?: boolean;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Page_DocumentOut_'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_document_api_documents__document_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        document_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DocumentOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_document_api_documents__document_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        document_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_document_text_api_documents__document_id__text_get: {
    parameters: {
      query?: {
        offset?: number;
        length?: number;
      };
      header?: never;
      path: {
        document_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DocumentText'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  move_document_api_documents__document_id__move_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        document_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MoveDocument'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DocumentOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  reject_document_api_documents__document_id__reject_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        document_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RejectDocument'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DocumentOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
}
